import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";

// Tokens are generated by the database as 48 hex characters; anything that
// clearly is not a token is rejected before it reaches the database.
const TOKEN_PATTERN = /^[A-Za-z0-9_-]{16,128}$/;

export type PublicShareLink = {
  id: string;
  file_id: string;
  password_hash: string | null;
  allow_download: boolean;
  expires_at: string | null;
  disabled: boolean;
};

export type ShareLinkLookup =
  | { status: "active"; link: PublicShareLink }
  | { status: "not_found" | "disabled" | "expired" };

/** Response headers for public-share endpoints: links must never be cached. */
export const NO_STORE_HEADERS = { "Cache-Control": "private, no-store" };

/**
 * Resolves a public share token to its link row and reports whether the link
 * is currently usable. Password and download checks are left to the caller.
 */
export async function lookupShareLink(
  supabase: SupabaseClient,
  token: string
): Promise<ShareLinkLookup> {
  if (!TOKEN_PATTERN.test(token)) return { status: "not_found" };

  const { data: link, error } = await supabase
    .from("share_links")
    .select("id, file_id, password_hash, allow_download, expires_at, disabled")
    .eq("token", token)
    .maybeSingle<PublicShareLink>();

  if (error || !link?.file_id) return { status: "not_found" };
  if (link.disabled) return { status: "disabled" };
  if (link.expires_at && new Date(link.expires_at) <= new Date()) {
    return { status: "expired" };
  }
  return { status: "active", link };
}
